# checks to run on branches for each pull request
name: branch-checks

on:
  pull_request:

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Run shared unit tests
      run: |
        pip install -r requirements/requirements_development.txt
        pip install -r requirements/requirements.txt
        pip freeze
        python -m pytest shared
